version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - victorheringer
  - murillo94
  - julianosbento
  - an-mag
  - pleaobraga
  - carlosberti
  - lopesalysson
  - pedro-cerdera
  - caiogodoi
  assignees:
  - victorheringer
  - murillo94
  - julianosbento
  - an-mag
  - pleaobraga
  - carlosberti
  - lopesalysson
  - pedro-cerdera
  - caiogodoi
  ignore:
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
