version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - julianosbento
  - an-mag
  - lopesalysson
  - pedro-cerdera
  - lucianomlima
  - albertozaranza
  - Michele-Camargo
