---
root: true

env:
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - prettier

plugins:
  - prettier
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2015
  ecmaFeatures:
    jsx: true
    modules: true
  sourceType: module

rules:
  no-undef: 0
  no-unused-vars: 2
  prettier/prettier: 2
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/no-unused-vars": 2
