version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"

    default_reviewers:
      - "victorheringer"
      - "murillo94"
      - "julianosbento"
      - "an-mag"
      - "pleaobraga"
      - "carlosberti"
      - "lopesalysson"
      - "pedro-cerdera"
      - "caiogodoi"
    default_assignees:
      - "victorheringer"
      - "murillo94"
      - "julianosbento"
      - "an-mag"
      - "pleaobraga"
      - "carlosberti"
      - "lopesalysson"
      - "pedro-cerdera"
      - "caiogodoi"
